inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive
